import { StyleSheet, Dimensions } from "react-native";

const {height, width} = Dimensions.get('window');
const styles = StyleSheet.create({
    startContainer:{
        flex:1,
        margin:15,
        paddingTop:20,
    },
    buttonGo:{
        marginTop:27,
        marginLeft:20,
        marginRight:20,
        borderWidth:1.5,
        borderColor:'black',
        borderRadius:25,
    },
    imageStart:{
        width:'100%',
        height:'100%',
        borderRadius:30,
    },
    txtGo:{
        fontSize:23,
        textAlign:'center',
        padding:10,
    },
    logoText:{
        fontWeight:'bold',
        fontSize:42,
        textAlign:'justify'
    },
    categoryContainer:{
        flex:1,
        padding:20,
        backgroundColor:'white'
    },
    headercategory:{
        height:'8%',
        marginTop:20,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    textHeader:{
        fontSize:15,
        color:'gray'
    },
    imageHeader:{
        width:50,
        height:50,
        borderRadius:30,
    },
    bannerContainer:{
        height:'20%',
        marginTop:15,
    },
    searchContainer:{
        marginTop:15,
        paddingLeft:5,
        flexDirection:'row',
        alignItems:'center',
        borderWidth:1,
        borderColor:'gray',
        borderRadius:22,
        height:'6.4%'
    },
    searchText:{
        width:'90%',
        height:45,
        borderWidth:0,
        fontSize:16,
        paddingLeft:15,
        paddingRight:13
    },
    listCategory:{
        centerContent:true,
        marginTop:10,
        flexDirection:'row',
        justifyContent:'space-between',

    },
    buttonCategory:{
        backgroundColor: '#E4E2E2',
        width:100,
        height:40,
        borderRadius:20,
        justifyContent:'center',
        marginRight:20
    },
    btnCategoryText:{
        textAlign:'center',
        fontSize:18
    },
    listContainer:{
        width:'49%',
        height:320,
        marginRight:10
    },
    itemContainer:{
        width:'100%',
        elevation:30,
        shadowColor:'black',
        backgroundColor:'white',
        borderRadius:20
    },
    imageItem:{
        width:'100%',
        height:'70%',
        borderRadius:20,
       
    },
    itemText:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-around'
    },
    textName:{
        backgroundColor:'white',
        fontWeight:'bold',
        margin:5,
    },
    textPrice:{
        backgroundColor:'white',
        fontWeight:'bold',
        marginLeft:5,
        //DC9100
    },
    
    
})
export default styles